config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get '/search', to: 'search#search'
  post '/search/filter', to: 'search#search', as: 'search_filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
    include Elasticsearch::Model

end

app/models/skill.rb
class Skill < ApplicationRecord
    include Elasticsearch::Model

end

app/models/user.rb
class User < ApplicationRecord
    has_many :skills
    has_one :rating

    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings do
        mappings dynamic: false do
          indexes :id, type: :keyword
          indexes :name, type: :text
          indexes :email, index: false
          indexes :photo, index: false
          indexes :country, type: :text, analyzer: :english
          indexes :skills, type: :nested do
            indexes :name, type: :text
            indexes :description, type: :text
          end
          indexes :rating, type: :nested do
            indexes :value, type: :text
          end
        end
      end

      def as_indexed_json(_options = nil)
        as_json(
          only: [:name, :email, :country],
          include: {
            rating: {
              only: [:value]
            },
            skills: {
              only: [:name, :description]
            }
          }
        )
      end

      def self.search_query(query)
        search(
          query: {
              bool: {
                should: [
                    {
                        multi_match: {
                            query: query,
                            fuzziness: 'AUTO',
                            fields: %w[name country]
                        }
                    },
                    {
                        nested: {
                            path: 'rating',
                            query: {
                                multi_match: {
                                    query: query,
                                    fields: ['rating.value']
                                }
                            }
                        }
                    },
                    {
                        nested: {
                            path: 'skills',
                            query: {
                                multi_match: {
                                    query: query,
                                    fuzziness: 'AUTO',
                                    fields: %w[skills.name skills.description]
                                }
                            }
                        }
                    }
                ],           
             }        
          }
        )
      end

      def self.search_all 
        search(
          query: {
            match_all: {}
          },
          aggs: {
            unique_ids: {
                terms: {
                    field: "id"
                }
            }
          }
        )
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def index 
        @users = User.search_all
    end

    def search

        query = params[:query].to_s
        return all_users if query.empty?

        @users = User.search_query(query)       
        
        render "search/_search"
    end


    private

    def all_users
        @users = User.search_all
        render "search/_search"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/_search.html.erb
<div class="card-columns m-5">
  <% @users.each do | user | %>
    <%= render partial: 'shared/card', locals: { user: user }  %>
  <% end %>
</div>


 

app/views/search/index.html.erb
<div class="container-fluid">
  <div data-controller="search" class="w-100">
    <nav class="navbar navbar-light bg-light">
      <form
      class="form-inline"
      data-action="ajax:success->search#result"
        data-action="ajax:error->search#error"
        data-target="search.form"
        data-remote="true"
        method="post"
        action="<%= search_filter_path %>"
        >
        <input
        class="form-control mr-sm-2"
        aria-label="Search"
        data-action="keyup->search#search"
          data-target="search.query"
          type="search" 
          name="query" 
          value=""
          placeholder="Search"
          />
        </form>
      </nav>

      <div class="container" data-target="search.display">
        <%= render partial: 'search', collection: @users %>
      </div>
      
    </div>
  </div>

app/views/shared/_card.html.erb
<div class="card">
  <img class="card-img-top img-thumbnail" src="https://www.nicepng.com/png/full/608-6080578_png-file-svg-icono-de-persona-png.png" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= user.name %></h5>
    <p class="card-text">
      <ul>
        <li><strong>Email:</strong> <%= user.email %></li>
        <li><strong>Country:</strong> <%= user.country %></li>
      </ul>
    </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
    <strong>Skills</strong>
    <br/>
      <% user.skills.each do | skill | %>
        <span class="badge badge-pill badge-primary">
          <%= skill.name %>
        </span>
      <% end %>
    </li>
    <li class="list-group-item">
    <strong>Rating</strong>
    <br/>
     <% 5.times.each_with_index  do | rating, index | %>
        <span class="<%= (user.rating.value.to_i >= index + 1) ? "fas fa-star checked" : "fas fa-star unchecked"  %>"></span>
      <% end %>

    </li>
  </ul>
</div>